### PR TITLE
Fix bug with byte[] / base64 handling and array handling in general

### PR DESCRIPTION
**Pull request by antony-scott**
Thanks for creating this, I've found it very useful so far. However, I found an issue when handling byte[], the parameter for the RequestBody would get serialised as an empty `<struct />` tag. I've fixed this issue and also another issue around array handling in general.

There is also a unit test project to highlight the issues.

I created a myget account and uploaded a test [package](https://www.myget.org/feed/antonyscott/package/nuget/RestSharp.Rpc.antony-scott) there so I could test it in my spike application.

### CODE REVIEW

**Comment by antony-scott** [comment]
I'd missed out the base64 encoding! I'll be back

**Comment by dallasbeek** [comment]
Antony, thank you for the kind words and I look forward to merging your corrections in.  The RPC API I wrote this for didn't have very complex input parameters so some of the serialization was written in the dark.  

I saw you added an OrderByAttribute.  I think RestSharp has an Index property for the SerializeAs
[SerializeAs(Index =3]).  Maybe that would be more appropriate here.  I tried to keep as much of the original RestSharp serializer/deserializer as I could, so it is possible that may already work.

Let me know when you get the base 64 encoding implemented.  I'm not sure if you can check the deserialization of byte[], I'm not totally sure that is right.

**Comment by dallasbeek** [comment]
Antony,
I rewrote the Serializer as I discovered several issues with complex objects.  I published a branch byte-support where I pulled some of your changes in.  I did discover that the Serialize(Index) worked so I did not pull your order by into the project.  Would you mind reviewing the branch.  If I don't hear back from you I will publish to nuget this weekend.

Dallas

**Comment by antony-scott** [comment]
I've just had a look through the changes and it looks good. I see you've done the base64 conversion almost exactly as I did it. Although since the `obj is byte[]` is true I did a simple cast rather than an `as`. I'll give it another go with my use case once you've published.

**Comment by dallasbeek** [comment]
It is published. 1.0.3

**Comment by antony-scott** [comment]
Thanks. I pulled the code into by local repo and tried it out. I've put a fix in to handle arrays of complex objects, this time using the `SerializeAs` attribute. I'm not sure if the service I'm calling is producing badly format xml-rpc responses, but the fix seems to work for my particular use case. I've added a test, but for some reason the xml file loading code pattern you've used isn't working for my test runner (Resharper) so I've hard coded a path for now. I'll look into it in more detail another day and try and put together another pull request.

**Comment by dallasbeek** [comment]
Would you mind attaching the response you are trying to deserialize and the class(es) you are trying to deserialize them to?

**Comment by dallasbeek** [comment]
For the file loading can you let me know if this works with Resharper.  Change the OneStringResponse.xml file to an Embedded resource and load it this way.

` 
        private string GetResource ( string name ) {
            Assembly a = Assembly.GetExecutingAssembly();
            using ( Stream s = a.GetManifestResourceStream( "RestSharp.Rpc.Tests.ResponseData." + name ) ) {
               using ( StreamReader sr = new StreamReader( s ) ) {
                  return sr.ReadToEnd();
               }
            }
         }

         [Test]
         public void DeserializeOneString () {
            var response = new RestResponse();
            response.Content = GetResource("OneStringResponse.xml" );
            var deSerializer = new XmlRpcDeserializer();
            var data = deSerializer.Deserialize<RpcResponseValue<string>>( response );
            Assert.AreEqual( "Hello World", data.Value );
         }

`

**Comment by antony-scott** [comment]
thanks. I was planning to use embedded resources as a way of getting the tests passing :)
I've modified all the tests to use embedded resources and all are now passing in the Resharper test runner.

I've pushed some changesets to update the tests and to include the (badly formed?) XML-RPC response I've been trying to deserialise. I'm new to pull requests and git in general, but I think those changesets have been automatically included in the pull request.

If the response I'm dealing with, which I am using from an external API and cannot change, does turn out to be badly formed. I think including the ability to cope with that by decorating the target class with attributes is a good way of handling that situation.

**Pull request closed without merging**
