### PR TITLE
Antony

### PR DESCRIPTION
**Pull request by dallasbeek**

### CODE REVIEW

**Review by antony-scott — APPROVED** [review]

**Comment by dallasbeek** [comment]
Hi Antony,  I've published a branch named tests for your review

Over the weekend, I was thinking about how much I didn't like my test case for DeserializeArrayOfMixed which basically mapped a mixed array (which is what your file name structures are) to List<object>.  I added some logic that uses the DeserializeAs attribute and logic to track the index of the requested deserialize (i.e. second string gets mapped to the second property that specifies DeserializeAs string).  The test case DeserializeArrayOfMixedToObject was created to deserialize a mixed array to an object.  As I think about the SerializeAs it probably wasn't meant to be used in Deserialization.  So using the DeserializeAs I have reworked what you are trying to do (See DeserializeArrayOfMixedArray test case).  I want to do a bit more testing by adding a struct and some more complexity as this feels like it is missing something.  Let me know what you think.

**Comment by antony-scott** [comment]
Nice, I've just tried it with a much more complex example and it works well.

**Comment by dallasbeek** [comment]
1.0.4 nuget published, I'm beginning work on JSON RPC (branch json).  Have you worked with JSON RPC?  Again coding in the dark :)

**Comment by antony-scott** [comment]
Good news on the nuget update. I'll pull the new version down and try it
out in my spike. Regarding JSON RPC, I didn't even know about it until just
now. I've just had a quick scan of the wikipedia page on it and it seems to
me that, if the object structure is the same, it's "just" a different
serialisation method.

**Pull request closed without merging**
